# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Stepan\Desktop\PYQT\design\messenger.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1111, 810)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inputMessage = QtWidgets.QLineEdit(self.centralwidget)
        self.inputMessage.setGeometry(QtCore.QRect(200, 760, 831, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.inputMessage.setFont(font)
        self.inputMessage.setObjectName("inputMessage")
        self.sendMessageBtn = QtWidgets.QPushButton(self.centralwidget)
        self.sendMessageBtn.setGeometry(QtCore.QRect(1040, 760, 51, 41))
        self.sendMessageBtn.setObjectName("sendMessageBtn")
        self.usersList = QtWidgets.QListWidget(self.centralwidget)
        self.usersList.setGeometry(QtCore.QRect(10, 60, 181, 691))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.usersList.setFont(font)
        self.usersList.setObjectName("usersList")
        self.findPersonBtn = QtWidgets.QPushButton(self.centralwidget)
        self.findPersonBtn.setGeometry(QtCore.QRect(10, 30, 181, 21))
        self.findPersonBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.findPersonBtn.setObjectName("findPersonBtn")
        self.personInfo = QtWidgets.QLabel(self.centralwidget)
        self.personInfo.setGeometry(QtCore.QRect(210, 9, 571, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.personInfo.setFont(font)
        self.personInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.personInfo.setObjectName("personInfo")
        self.changeKey = QtWidgets.QPushButton(self.centralwidget)
        self.changeKey.setGeometry(QtCore.QRect(970, 10, 121, 41))
        self.changeKey.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.changeKey.setObjectName("changeKey")
        self.keyInput = QtWidgets.QLineEdit(self.centralwidget)
        self.keyInput.setGeometry(QtCore.QRect(760, 10, 201, 41))
        self.keyInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.keyInput.setObjectName("keyInput")
        self.findPersonInput = QtWidgets.QLineEdit(self.centralwidget)
        self.findPersonInput.setGeometry(QtCore.QRect(10, 5, 181, 22))
        self.findPersonInput.setObjectName("findPersonInput")
        self.MessagesList = QtWidgets.QTextEdit(self.centralwidget)
        self.MessagesList.setGeometry(QtCore.QRect(200, 60, 891, 691))
        self.MessagesList.setReadOnly(True)
        self.MessagesList.setObjectName("MessagesList")
        self.settingsBtn = QtWidgets.QPushButton(self.centralwidget)
        self.settingsBtn.setGeometry(QtCore.QRect(10, 760, 181, 41))
        self.settingsBtn.setObjectName("settingsBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ANON"))
        self.inputMessage.setPlaceholderText(_translate("MainWindow", "Написать сообщение..."))
        self.sendMessageBtn.setText(_translate("MainWindow", ">"))
        self.findPersonBtn.setText(_translate("MainWindow", "Найти человека"))
        self.personInfo.setText(_translate("MainWindow", "TextLabel"))
        self.changeKey.setText(_translate("MainWindow", "Сменить ключ"))
        self.keyInput.setPlaceholderText(_translate("MainWindow", "Ключ..."))
        self.MessagesList.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.13913pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">[12:23]  Коллега Влад: Мммм Potentia</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">[12:23]  Я: Кеклик</span></p></body></html>"))
        self.settingsBtn.setText(_translate("MainWindow", "Настройки"))
