# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Stepan\Desktop\PYQT\settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(331, 152)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 114, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:#708499")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 30, 191, 27))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 84, 191, 27))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 30, 89, 27))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 84, 89, 27))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto Light")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:#708499")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Настройки"))
        self.label_2.setText(_translate("MainWindow", "Имя пользователя"))
        self.lineEdit.setText(_translate("MainWindow", "Степанидзе"))
        self.lineEdit_2.setInputMask(_translate("MainWindow", "@nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn"))
        self.lineEdit_2.setText(_translate("MainWindow", "@Stepashka20"))
        self.pushButton.setText(_translate("MainWindow", "Сохранить"))
        self.pushButton_2.setText(_translate("MainWindow", "Сохранить"))
        self.label_3.setText(_translate("MainWindow", "Имя"))
